pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
    plugins {
        id "org.jetbrains.kotlin.plugin.compose" version "2.3.0"
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        flatDir {
            dirs("app/libs")
        }
        maven {
            name = "CentralPortalSnapshots"
            url = uri("https://central.sonatype.com/repository/maven-snapshots/")
            // Only look here for snapshots (and optionally for a specific group)
            mavenContent {
                snapshotsOnly()
                includeGroup("com.finix")   // optional but recommended
            }
        }
    }
}

rootProject.name = "SampleTokenize"
include ':app'
